Fix build error due to dependency change
Build error - github.com/yvasiyarov/gorelic/agent.go:133: not enough arguments in call to newrelic_platform_go.NewPluginComponent